/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package credits.ui;

import commons.NavigationUtil;
import javax.swing.JFrame;

/**
 *
 * @author Joko
 */
public class CreditsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreditsUI.class.getName());

    private JFrame parent; // Pass the previous frame
    
    public CreditsUI(JFrame parent) {
        setUndecorated(true);
        this.parent = parent;
        initComponents();
        setSize(1920, 1080);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new commons.RoundButton();
        btnMinimize = new commons.RoundButton();
        btnExit = new commons.RoundButton();
        pnlBody = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 22, 48));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(0, 0));

        Header.setBackground(new java.awt.Color(45, 45, 114));
        Header.setPreferredSize(new java.awt.Dimension(1920, 77));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREDITS");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 10, 183, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 177, 223));
        jLabel3.setText("Team and Instructor");
        Header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 46, 183, -1));

        btnBack.setBorder(null);
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorderColor(new java.awt.Color(75, 74, 151));
        btnBack.setBorderEnabled(false);
        btnBack.setBorderPainted(false);
        btnBack.setColor(new java.awt.Color(75, 74, 151));
        btnBack.setColorClick(new java.awt.Color(48, 43, 116));
        btnBack.setColorOver(new java.awt.Color(48, 43, 116));
        btnBack.setFocusable(false);
        btnBack.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnBack.setRadius(10);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Header.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1653, 18, 136, 39));

        btnMinimize.setBorder(null);
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("–");
        btnMinimize.setBorderColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setBorderEnabled(false);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setColorClick(new java.awt.Color(48, 43, 116));
        btnMinimize.setColorOver(new java.awt.Color(48, 43, 116));
        btnMinimize.setFocusable(false);
        btnMinimize.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnMinimize.setRadius(10);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        Header.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1801, 18, 40, 39));

        btnExit.setBackground(new java.awt.Color(219, 60, 172));
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("x");
        btnExit.setBorderColor(new java.awt.Color(219, 60, 172));
        btnExit.setBorderEnabled(false);
        btnExit.setBorderPainted(false);
        btnExit.setColor(new java.awt.Color(219, 60, 172));
        btnExit.setColorClick(new java.awt.Color(153, 62, 145));
        btnExit.setColorOver(new java.awt.Color(153, 62, 145));
        btnExit.setFocusable(false);
        btnExit.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnExit.setRadius(10);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        Header.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1853, 18, 40, 39));

        getContentPane().add(Header, java.awt.BorderLayout.NORTH);

        pnlBody.setBackground(new java.awt.Color(14, 22, 48));
        pnlBody.setMaximumSize(new java.awt.Dimension(1920, 32767));
        pnlBody.setMinimumSize(new java.awt.Dimension(1920, 0));
        pnlBody.setPreferredSize(new java.awt.Dimension(1920, 823));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Meet the Project Team and Instructor");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credits/icons/TeamFrame.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credits/icons/TeacherFrame.png"))); // NOI18N

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(551, 551, 551)))))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBody, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        NavigationUtil.switchFrame(this, parent);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private commons.RoundButton btnBack;
    private commons.RoundButton btnExit;
    private commons.RoundButton btnMinimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlBody;
    // End of variables declaration//GEN-END:variables
}
