/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.UI;

import commons.UIPositionUtil;
import credits.ui.CreditsUI;
import dashboard.roles.UserRoles;
import datavisualization.charts;
import quiz.QuizUI;
import static commons.UIPositionUtil.*;


import javax.swing.JFrame;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;



/**
 *
 * @author Joko
 */
public class DashboardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardUI.class.getName());
    private UserRoles role;
    
    QuizUI Quizframe = new QuizUI();
    charts DataVisframe = new charts();
    CreditsUI Creditsframe = new CreditsUI(this);
    
    public DashboardUI(UserRoles role) {
        setUndecorated(true);
        this.role = role;
        
        initComponents();
        this.setVisible(true);
        startDateTime();
        
        pnlBody.setLayout(null); // VERY IMPORTANT
        pnlSidebarOptions.setLayout(null); // VERY IMPORTANT
        applyRoleConfig();
        
        pnlBody.revalidate();
        pnlBody.repaint();
        
        pnlSidebarOptions.revalidate();
        pnlSidebarOptions.repaint();
    }
    
    private void applyRoleConfig() {

        QuizCard.setVisible(false);
        CreditCard.setVisible(false);
        DataVisCard.setVisible(false);
        ChatbotCard.setVisible(false);

        switch (role) {

            case ADMIN:
                setupCard(QuizCard, "/dashboard/icons/AdminQuizCard.png", 40, 150, 1054, 347);                  
                setupCard(ChatbotCard, "/dashboard/icons/AdminChatbotCard.png", 580, 520, 1054, 443);
                setupCard(DataVisCard, "/dashboard/icons/AdminDataVisCard.png", 40, 520, 509, 443);
                setupCard(CreditCard, "/dashboard/icons/AdminCreditsCard.png", 1120, 150, 509, 345);
                setupCard(ProfilePic, "/dashboard/icons/AdminUserProfile.png", 70, 31, 123, 161);
                
                Title.setText("Welcome Joko!");
                break;

            case USER:
                setupCard(QuizCard, "/dashboard/icons/UserQuizCard.png", 40, 120, 1598, 373);            
                setupCard(ChatbotCard, "/dashboard/icons/UserChatbotCard.png", 40, 520, 1054, 443);
                setupCard(CreditCard, "/dashboard/icons/UserCreditsCard.png", 1120, 520, 509, 443);
                
                UIPositionUtil.move(btnQuiz, 740, 340);
                UIPositionUtil.move(btnChatbot, 80, 870);
                UIPositionUtil.move(btnCredits, 1270, 850);
                
                btnDataVis.setVisible(false);
                
                setupCard(ProfilePic, "/dashboard/icons/UserProfile.png", 45, 31, 172, 161);
                
                Title.setText("Welcome Luisa!");
                break;

            case GUEST:
                setupCard(DataVisCard, "/dashboard/icons/GuestDataVisCard.png", 40, 150, 782, 835);
                setupCard(CreditCard, "/dashboard/icons/GuestCreditsCard.png", 850, 150, 781, 835);
                
                UIPositionUtil.move(btnDataVis, 330, 780);
                UIPositionUtil.move(btnCredits, 1135, 770);
                
                btnQuiz.setVisible(false);
                btnChatbot.setVisible(false);
                
                setupCard(ProfilePic, "/dashboard/icons/GuestProfile.png", 70, 31, 123, 161);
                
                Title.setText("Welcome Pat!");
                break;
        }

        pnlBody.revalidate();
        pnlBody.repaint();
        pnlSidebarOptions.revalidate();
        pnlSidebarOptions.repaint();
    }

    
    
    private void startDateTime() {
        DateTimeFormatter formatter =
        DateTimeFormatter.ofPattern("EEEE, MMMM dd, yyyy | hh:mm a");

        Timer timer = new Timer(1000, e -> {
            jLabel3.setText(LocalDateTime.now().format(formatter));
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        pnlSidebarHeader = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        LogoName = new javax.swing.JLabel();
        pnlSidebarOptions = new javax.swing.JPanel();
        ProfilePic = new javax.swing.JLabel();
        btnSbChatbot = new commons.RoundButton();
        btnSbDashboard = new commons.RoundButton();
        btnSbTakeQuiz = new commons.RoundButton();
        btnSbDataVis = new commons.RoundButton();
        btnSbCredits = new commons.RoundButton();
        btnLogout = new commons.RoundButton();
        pnlPlaceholder = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMinimize = new commons.RoundButton();
        btnExit = new commons.RoundButton();
        pnlBody = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Subtitle = new javax.swing.JLabel();
        btnChatbot = new commons.GradientButton();
        btnDataVis = new commons.GradientButton();
        btnCredits = new commons.GradientButton();
        btnQuiz = new commons.GradientButton();
        CreditCard = new javax.swing.JLabel();
        QuizCard = new javax.swing.JLabel();
        DataVisCard = new javax.swing.JLabel();
        ChatbotCard = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(255, 153, 153));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(262, 1080));
        pnlSidebar.setLayout(new java.awt.BorderLayout());

        pnlSidebarHeader.setBackground(new java.awt.Color(31, 35, 84));
        pnlSidebarHeader.setPreferredSize(new java.awt.Dimension(262, 77));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/LEARNLogo.png"))); // NOI18N

        LogoName.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        LogoName.setForeground(new java.awt.Color(255, 255, 255));
        LogoName.setText("LEARN");

        javax.swing.GroupLayout pnlSidebarHeaderLayout = new javax.swing.GroupLayout(pnlSidebarHeader);
        pnlSidebarHeader.setLayout(pnlSidebarHeaderLayout);
        pnlSidebarHeaderLayout.setHorizontalGroup(
            pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSidebarHeaderLayout.setVerticalGroup(
            pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                .addGroup(pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo))
                    .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LogoName)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlSidebar.add(pnlSidebarHeader, java.awt.BorderLayout.NORTH);

        pnlSidebarOptions.setBackground(new java.awt.Color(28, 32, 77));
        pnlSidebarOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlSidebarOptions.add(ProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 31, -1, -1));

        btnSbChatbot.setForeground(new java.awt.Color(255, 255, 255));
        btnSbChatbot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconChatbot.png"))); // NOI18N
        btnSbChatbot.setText("Simple Chatbot");
        btnSbChatbot.setBorderEnabled(false);
        btnSbChatbot.setColor(new java.awt.Color(28, 32, 77));
        btnSbChatbot.setColorClick(new java.awt.Color(44, 45, 108));
        btnSbChatbot.setColorOver(new java.awt.Color(44, 45, 108));
        btnSbChatbot.setFocusable(false);
        btnSbChatbot.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSbChatbot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSbChatbot.setIconTextGap(15);
        btnSbChatbot.setPaddingLeft(23);
        btnSbChatbot.setPaddingRight(20);
        btnSbChatbot.setRadius(20);
        pnlSidebarOptions.add(btnSbChatbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 357, 262, 61));

        btnSbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnSbDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconDashboard.png"))); // NOI18N
        btnSbDashboard.setText("Dashboard");
        btnSbDashboard.setBorderEnabled(false);
        btnSbDashboard.setColor(new java.awt.Color(44, 45, 108));
        btnSbDashboard.setColorClick(new java.awt.Color(44, 45, 108));
        btnSbDashboard.setColorOver(new java.awt.Color(44, 45, 108));
        btnSbDashboard.setFocusable(false);
        btnSbDashboard.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSbDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSbDashboard.setIconTextGap(15);
        btnSbDashboard.setPaddingLeft(23);
        btnSbDashboard.setPaddingRight(20);
        btnSbDashboard.setRadius(20);
        pnlSidebarOptions.add(btnSbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 233, 262, 61));

        btnSbTakeQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btnSbTakeQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconTakeQuiz.png"))); // NOI18N
        btnSbTakeQuiz.setText("Take Quiz");
        btnSbTakeQuiz.setBorderEnabled(false);
        btnSbTakeQuiz.setColor(new java.awt.Color(28, 32, 77));
        btnSbTakeQuiz.setColorClick(new java.awt.Color(44, 45, 108));
        btnSbTakeQuiz.setColorOver(new java.awt.Color(44, 45, 108));
        btnSbTakeQuiz.setFocusable(false);
        btnSbTakeQuiz.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSbTakeQuiz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSbTakeQuiz.setIconTextGap(15);
        btnSbTakeQuiz.setPaddingLeft(23);
        btnSbTakeQuiz.setPaddingRight(20);
        btnSbTakeQuiz.setRadius(20);
        btnSbTakeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbTakeQuizActionPerformed(evt);
            }
        });
        pnlSidebarOptions.add(btnSbTakeQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 262, 61));

        btnSbDataVis.setForeground(new java.awt.Color(255, 255, 255));
        btnSbDataVis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconDataVis.png"))); // NOI18N
        btnSbDataVis.setText("Data Visualization");
        btnSbDataVis.setBorderEnabled(false);
        btnSbDataVis.setColor(new java.awt.Color(28, 32, 77));
        btnSbDataVis.setColorClick(new java.awt.Color(44, 45, 108));
        btnSbDataVis.setColorOver(new java.awt.Color(44, 45, 108));
        btnSbDataVis.setFocusable(false);
        btnSbDataVis.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSbDataVis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSbDataVis.setIconTextGap(15);
        btnSbDataVis.setPaddingLeft(23);
        btnSbDataVis.setPaddingRight(20);
        btnSbDataVis.setRadius(20);
        btnSbDataVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbDataVisActionPerformed(evt);
            }
        });
        pnlSidebarOptions.add(btnSbDataVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 262, 61));

        btnSbCredits.setForeground(new java.awt.Color(255, 255, 255));
        btnSbCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconCredits.png"))); // NOI18N
        btnSbCredits.setText("Credits");
        btnSbCredits.setBorderEnabled(false);
        btnSbCredits.setColor(new java.awt.Color(28, 32, 77));
        btnSbCredits.setColorClick(new java.awt.Color(44, 45, 108));
        btnSbCredits.setColorOver(new java.awt.Color(44, 45, 108));
        btnSbCredits.setFocusable(false);
        btnSbCredits.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSbCredits.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSbCredits.setIconTextGap(15);
        btnSbCredits.setPaddingLeft(23);
        btnSbCredits.setPaddingRight(20);
        btnSbCredits.setRadius(20);
        btnSbCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbCreditsActionPerformed(evt);
            }
        });
        pnlSidebarOptions.add(btnSbCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 479, 262, 61));

        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/IconLogout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorderEnabled(false);
        btnLogout.setColor(new java.awt.Color(28, 32, 77));
        btnLogout.setColorClick(new java.awt.Color(44, 45, 108));
        btnLogout.setColorOver(new java.awt.Color(44, 45, 108));
        btnLogout.setFocusable(false);
        btnLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(15);
        btnLogout.setPaddingLeft(23);
        btnLogout.setPaddingRight(20);
        btnLogout.setRadius(20);
        pnlSidebarOptions.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 901, 262, 61));

        pnlSidebar.add(pnlSidebarOptions, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pnlPlaceholder.setBackground(new java.awt.Color(204, 255, 102));
        pnlPlaceholder.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(45, 45, 114));
        Header.setPreferredSize(new java.awt.Dimension(1658, 77));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 177, 223));
        jLabel3.setText("Loading date & time…");

        btnMinimize.setBorder(null);
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("–");
        btnMinimize.setBorderColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setBorderEnabled(false);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setColorClick(new java.awt.Color(48, 43, 116));
        btnMinimize.setColorOver(new java.awt.Color(48, 43, 116));
        btnMinimize.setFocusable(false);
        btnMinimize.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnMinimize.setRadius(10);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(219, 60, 172));
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("x");
        btnExit.setBorderColor(new java.awt.Color(219, 60, 172));
        btnExit.setBorderEnabled(false);
        btnExit.setBorderPainted(false);
        btnExit.setColor(new java.awt.Color(219, 60, 172));
        btnExit.setColorClick(new java.awt.Color(153, 62, 145));
        btnExit.setColorOver(new java.awt.Color(153, 62, 145));
        btnExit.setFocusable(false);
        btnExit.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnExit.setRadius(10);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1192, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlPlaceholder.add(Header, java.awt.BorderLayout.NORTH);

        pnlBody.setBackground(new java.awt.Color(14, 22, 48));
        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Welcome Joko!");
        pnlBody.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 23, 314, -1));

        Subtitle.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        Subtitle.setForeground(new java.awt.Color(182, 181, 228));
        Subtitle.setText("Learn something new today.");
        pnlBody.add(Subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 73, 479, -1));

        btnChatbot.setText("CHAT NOW");
        btnChatbot.setColor1(new java.awt.Color(109, 31, 239));
        btnChatbot.setColor2(new java.awt.Color(234, 46, 201));
        btnChatbot.setFocusable(false);
        btnChatbot.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnChatbot.setHoverColor1(new java.awt.Color(158, 100, 255));
        btnChatbot.setHoverColor2(new java.awt.Color(244, 105, 220));
        pnlBody.add(btnChatbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 870, 200, 40));

        btnDataVis.setText("VIEW DATA");
        btnDataVis.setColor1(new java.awt.Color(109, 31, 239));
        btnDataVis.setColor2(new java.awt.Color(234, 46, 201));
        btnDataVis.setFocusable(false);
        btnDataVis.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnDataVis.setHoverColor1(new java.awt.Color(158, 100, 255));
        btnDataVis.setHoverColor2(new java.awt.Color(244, 105, 220));
        btnDataVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataVisActionPerformed(evt);
            }
        });
        pnlBody.add(btnDataVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 870, 200, 40));

        btnCredits.setText("VIEW CREDITS");
        btnCredits.setColor1(new java.awt.Color(109, 31, 239));
        btnCredits.setColor2(new java.awt.Color(234, 46, 201));
        btnCredits.setFocusable(false);
        btnCredits.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnCredits.setHoverColor1(new java.awt.Color(158, 100, 255));
        btnCredits.setHoverColor2(new java.awt.Color(244, 105, 220));
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });
        pnlBody.add(btnCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 410, 210, 40));

        btnQuiz.setText("START QUIZ");
        btnQuiz.setColor1(new java.awt.Color(109, 31, 239));
        btnQuiz.setColor2(new java.awt.Color(234, 46, 201));
        btnQuiz.setFocusable(false);
        btnQuiz.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnQuiz.setHoverColor1(new java.awt.Color(158, 100, 255));
        btnQuiz.setHoverColor2(new java.awt.Color(244, 105, 220));
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });
        pnlBody.add(btnQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 200, 40));

        CreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/AdminCreditsCard.png"))); // NOI18N
        CreditCard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBody.add(CreditCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, -1, -1));

        QuizCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/AdminQuizCard.png"))); // NOI18N
        QuizCard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBody.add(QuizCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        DataVisCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/AdminDataVisCard.png"))); // NOI18N
        pnlBody.add(DataVisCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        ChatbotCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/AdminChatbotCard.png"))); // NOI18N
        pnlBody.add(ChatbotCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));
        pnlBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        pnlPlaceholder.add(pnlBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPlaceholder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSbTakeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbTakeQuizActionPerformed
        btnSbTakeQuiz.addActionListener(e -> {
        if (role == UserRoles.GUEST) {
            JOptionPane.showMessageDialog(this,
                "Please login to access quizzes.");
            return;
        }
        Quizframe.setVisible(true);
});
        
        
    }//GEN-LAST:event_btnSbTakeQuizActionPerformed

    private void btnSbDataVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbDataVisActionPerformed
        DataVisframe.setVisible(true);
    }//GEN-LAST:event_btnSbDataVisActionPerformed

    private void btnSbCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbCreditsActionPerformed
        Creditsframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSbCreditsActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        Quizframe.setVisible(true);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
        Creditsframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreditsActionPerformed

    private void btnDataVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataVisActionPerformed
        DataVisframe.setVisible(true);
        
    }//GEN-LAST:event_btnDataVisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new DashboardUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChatbotCard;
    private javax.swing.JLabel CreditCard;
    private javax.swing.JLabel DataVisCard;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoName;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JLabel QuizCard;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JLabel Title;
    private commons.GradientButton btnChatbot;
    private commons.GradientButton btnCredits;
    private commons.GradientButton btnDataVis;
    private commons.RoundButton btnExit;
    private commons.RoundButton btnLogout;
    private commons.RoundButton btnMinimize;
    private commons.GradientButton btnQuiz;
    private commons.RoundButton btnSbChatbot;
    private commons.RoundButton btnSbCredits;
    private commons.RoundButton btnSbDashboard;
    private commons.RoundButton btnSbDataVis;
    private commons.RoundButton btnSbTakeQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlPlaceholder;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlSidebarHeader;
    private javax.swing.JPanel pnlSidebarOptions;
    // End of variables declaration//GEN-END:variables
}
