/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_page;


import commons.NavigationUtil;
import commons.UIUtils;
import dashboard.UI.DashboardUI;
import dashboard.roles.UserRoles;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author sirpa
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    private int Attempts = 3;
    /**
     * Creates new form login
     */
    
    // ADD THIS:  Static variable to store logged-in username
    private static String loggedInUsername = "Guest";
    
    // ADD THIS: Static getter method
    public static String getLoggedInUsername() {
        return loggedInUsername;
    }
    
    // ADD THIS: Static setter method
    public static void setLoggedInUsername(String username) {
        loggedInUsername = username;
    }
    
    public login() {
        setUndecorated(true);
        initComponents();
        setSize(1920, 1080);
        
        GraphicsDevice gd = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getDefaultScreenDevice();

        gd.setFullScreenWindow(this);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lblAttempts.setText(Attempts + " attempts remaining before program will close");
        lblPasswordNote.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new commons.RoundButton();
        btnMinimize = new commons.RoundButton();
        btnLogin = new commons.GradientButton();
        txtPassword = new javax.swing.JPasswordField();
        lblAttempts = new javax.swing.JLabel();
        btnContinueAsGuest = new javax.swing.JLabel();
        lblPasswordNote = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        LogoName = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        WelcomeBack = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        rbShowPassword = new javax.swing.JRadioButton();
        login_panel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("x");
        btnExit.setBorderColor(new java.awt.Color(219, 60, 172));
        btnExit.setBorderEnabled(false);
        btnExit.setBorderPainted(false);
        btnExit.setColor(new java.awt.Color(219, 27, 140));
        btnExit.setColorClick(new java.awt.Color(153, 62, 145));
        btnExit.setColorOver(new java.awt.Color(153, 62, 145));
        btnExit.setFocusable(false);
        btnExit.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnExit.setRadius(10);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1853, 23, 40, 40);

        btnMinimize.setBorder(null);
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("–");
        btnMinimize.setBorderColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setBorderEnabled(false);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setColorClick(new java.awt.Color(48, 43, 116));
        btnMinimize.setColorOver(new java.awt.Color(48, 43, 116));
        btnMinimize.setFocusable(false);
        btnMinimize.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnMinimize.setRadius(10);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimize);
        btnMinimize.setBounds(1801, 23, 40, 39);

        btnLogin.setText("LOGIN");
        btnLogin.setColor1(new java.awt.Color(109, 31, 239));
        btnLogin.setColor2(new java.awt.Color(234, 46, 201));
        btnLogin.setEnabled(false);
        btnLogin.setFocusable(false);
        btnLogin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        btnLogin.setHoverColor1(new java.awt.Color(158, 100, 255));
        btnLogin.setHoverColor2(new java.awt.Color(244, 105, 220));
        btnLogin.setSizeSpeed(1000.0F);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(730, 690, 450, 45);

        txtPassword.setBackground(new java.awt.Color(28, 32, 77));
        txtPassword.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(243, 233, 253));
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 181, 228), 1, true));
        txtPassword.setEchoChar('*');
        txtPassword.setFocusCycleRoot(true);
        txtPassword.setFocusTraversalPolicy(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(730, 500, 460, 30);

        lblAttempts.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblAttempts.setForeground(new java.awt.Color(243, 233, 253));
        lblAttempts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttempts.setText("3 attempts remaining before program will close");
        getContentPane().add(lblAttempts);
        lblAttempts.setBounds(730, 830, 460, 23);

        btnContinueAsGuest.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnContinueAsGuest.setForeground(new java.awt.Color(243, 233, 253));
        btnContinueAsGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnContinueAsGuest.setText("Continue as Guest");
        btnContinueAsGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinueAsGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinueAsGuestMouseClicked(evt);
            }
        });
        getContentPane().add(btnContinueAsGuest);
        btnContinueAsGuest.setBounds(800, 760, 310, 23);

        lblPasswordNote.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        lblPasswordNote.setForeground(new java.awt.Color(243, 233, 253));
        lblPasswordNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/Vector.png"))); // NOI18N
        lblPasswordNote.setText("<html>Password is required, must be at least 8 characters long<br>and include: Uppercase, Lowercase, Number </html>");
        lblPasswordNote.setFocusable(false);
        lblPasswordNote.setIconTextGap(10);
        getContentPane().add(lblPasswordNote);
        lblPasswordNote.setBounds(730, 590, 450, 50);

        lblUsername.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(243, 233, 253));
        lblUsername.setLabelFor(txtUsername);
        lblUsername.setText("Username");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(730, 370, 110, 16);

        LogoName.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        LogoName.setForeground(new java.awt.Color(255, 255, 255));
        LogoName.setText("LEARN");
        getContentPane().add(LogoName);
        LogoName.setBounds(930, 220, 86, 30);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/LEARNLogo.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(880, 210, 48, 47);

        lblPassword.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(243, 233, 253));
        lblPassword.setLabelFor(txtPassword);
        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(730, 470, 110, 16);

        WelcomeBack.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        WelcomeBack.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeBack.setText("Welcome Back!");
        WelcomeBack.setToolTipText("");
        WelcomeBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(WelcomeBack);
        WelcomeBack.setBounds(780, 270, 340, 80);

        txtUsername.setBackground(new java.awt.Color(28, 32, 77));
        txtUsername.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(243, 233, 253));
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 181, 228), 1, true));
        txtUsername.setCaretColor(new java.awt.Color(182, 181, 228));
        getContentPane().add(txtUsername);
        txtUsername.setBounds(730, 410, 460, 30);

        rbShowPassword.setBackground(new java.awt.Color(28, 32, 77));
        rbShowPassword.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        rbShowPassword.setForeground(new java.awt.Color(243, 233, 253));
        rbShowPassword.setText("Show Password");
        rbShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/State=Unselected.png"))); // NOI18N
        rbShowPassword.setIconTextGap(5);
        rbShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(rbShowPassword);
        rbShowPassword.setBounds(720, 550, 240, 30);

        login_panel.setForeground(new java.awt.Color(28, 32, 77));
        login_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/login_panel.png"))); // NOI18N
        login_panel.setToolTipText("");
        login_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(login_panel);
        login_panel.setBounds(680, 190, 559, 686);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/bg.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void rbShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbShowPasswordMouseClicked
        if(rbShowPassword.isSelected())
        {
            rbShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/State=Selected.png")));
            
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            rbShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_page/Images/State=Unselected.png")));
            
            txtPassword.setEchoChar('*');
        }
        
        repaint();
    }//GEN-LAST:event_rbShowPasswordMouseClicked
    private boolean isPasswordValid(String password)
    {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$";
        
         return   password.matches(regex);
        
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String usernameInput = txtUsername.getText();
        String passwordInput = new String(txtPassword.getPassword());
        
        if(usernameInput == null || usernameInput.length() < 1) 
        {
            UIUtils.showMessage(this, "Username field cannot be empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(passwordInput == null || passwordInput.length() < 1) 
        {
            UIUtils.showMessage(this, "Password field cannot be empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        
        
        DBConnection context = new DBConnection();
        System.out.println("password : " + passwordInput);
        User user = singleOrDefault(context.Users, 
                n -> (n.name.equals(usernameInput))
                    && (n.password.equals(passwordInput)));
        
        if(user == null) 
        {
            lblPasswordNote.setVisible(false);
            if(Attempts == 1)
            {
                System.exit(0);
            }
            System.out.println("Wrong Credentials");
            Attempts--;
            lblAttempts.setText(Attempts + " attempts remaining before program will close");
        } 
        else
        {
            // ADD THIS: Store the logged-in username
            lblPasswordNote.setVisible(false);
            login.setLoggedInUsername(user.name); // or usernameInput

            NavigationUtil.switchFrame(this, new DashboardUI(user.role));
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnContinueAsGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueAsGuestMouseClicked
        login.setLoggedInUsername("Guest");
        
        DashboardUI frm = new DashboardUI(UserRoles.GUEST);
        
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnContinueAsGuestMouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        String passwordInput = new String(txtPassword.getPassword());
        
        if(isPasswordValid(passwordInput))
        {
            lblPasswordNote.setVisible(false);
            btnLogin.setEnabled(true);
        }
        else
        {
            lblPasswordNote.setVisible(true);
            btnLogin.setEnabled(false);
        }
        
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }
    
    public static <T> T singleOrDefault(List<T> source, java.util.function.Predicate<T> predicate) {
        List<T> filteredList = source.stream()
                                     .filter(predicate)
                                     .collect(Collectors.toList());

        if (filteredList.isEmpty()) {
            return null; // Default value for reference types
        } else if (filteredList.size() == 1) {
            return filteredList.get(0);
        } else {
            throw new IllegalStateException("Sequence contains more than one matching element");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoName;
    private javax.swing.JLabel WelcomeBack;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnContinueAsGuest;
    private commons.RoundButton btnExit;
    private commons.GradientButton btnLogin;
    private commons.RoundButton btnMinimize;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordNote;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel login_panel;
    private javax.swing.JRadioButton rbShowPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
