package datavisualization.ui;

import javax.swing.JFrame;
import java.awt.*;
import javax.swing.*;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartPanel;
import datavisualization.charts.ChartFactoryUtil;
import datavisualization.data.SampleData;

public class DashBoardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashBoardUI.class.getName());
   
    private static final Color CARD_BG = Color.decode("#353080");
    
    public DashBoardUI() {
        setUndecorated(true);  
        initComponents();
        FullScreen();
        
        populateDashboard();
    }
    
    private void FullScreen(){
        this.setExtendedState(JFrame. MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        pnlInventory = new javax.swing.JPanel();
        pnlKpi = new javax.swing.JPanel();
        pnlRecs = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        pnlTrend = new javax.swing.JPanel();
        pnlPie = new javax.swing.JPanel();
        pnlLow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(14, 22, 48));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(14, 22, 48));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 48, 128));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 77));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 77));
        jPanel2.setPreferredSize(new java.awt.Dimension(1520, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 176, 200));
        jLabel2.setText("Inventory and Sales Monitoring");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, -1));

        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/icons/close-button.png"))); // NOI18N
        closeBtn.setIconTextGap(0);
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        jPanel2.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 20, -1, -1));

        minimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/icons/minimize-button.png"))); // NOI18N
        minimizeBtn.setIconTextGap(0);
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });
        jPanel2.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 238, 248));
        jLabel4.setText("DATA VISUALIZATION");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/icons/back-button.png"))); // NOI18N
        backBtn.setIconTextGap(0);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 20, -1, -1));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        pnlInventory.setBackground(new java.awt.Color(53, 48, 128));
        pnlInventory.setName(""); // NOI18N
        pnlInventory.setOpaque(false);
        pnlInventory.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 780, 520));

        pnlKpi.setBackground(new java.awt.Color(53, 48, 128));
        pnlKpi.setOpaque(false);
        pnlKpi.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlKpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 700, 190));

        pnlRecs.setBackground(new java.awt.Color(53, 48, 128));
        pnlRecs.setOpaque(false);
        pnlRecs.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlRecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 700, 290));

        pnlReport.setBackground(new java.awt.Color(53, 48, 128));
        pnlReport.setOpaque(false);
        pnlReport.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1578, 130, 320, 520));

        pnlTrend.setBackground(new java.awt.Color(53, 48, 128));
        pnlTrend.setOpaque(false);
        pnlTrend.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlTrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 1000, 370));

        pnlPie.setBackground(new java.awt.Color(53, 48, 128));
        pnlPie.setOpaque(false);
        pnlPie.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 690, 480, 370));

        pnlLow.setBackground(new java.awt.Color(53, 48, 128));
        pnlLow.setOpaque(false);
        pnlLow.setLayout(new java.awt.BorderLayout());
        mainPanel.add(pnlLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 690, 320, 370));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

// ============================================================================================================================        
    
    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
    }//GEN-LAST:event_closeBtnMouseExited

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited

    }//GEN-LAST:event_backBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked

    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked

    }//GEN-LAST:event_backBtnMouseClicked
    
// ============================================================================================================================    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() -> new DashBoardUI().setVisible(true));
    }

private static final java.awt.Font CARD_TITLE_FONT = new java.awt.Font("Montserrat", java.awt.Font.BOLD, 20);    
    
// Populate Placeholders
private void populateDashboard() {
    // Charts
    addChartCardTo(pnlInventory, ChartFactoryUtil.createInventoryBarChart(SampleData.getInventoryDataset()), "Inventory Levels per Category");
    addChartCardTo(pnlTrend,     ChartFactoryUtil.createMonthlyLineChart(SampleData.getMonthlyTrendDataset()), "Monthly Sales Trend");
    addChartCardTo(pnlPie,       ChartFactoryUtil.createSalesPieChart(SampleData.getSalesPieDataset()), "Sales by Product");

    // Info cards
    addPanelCardTo(pnlKpi,   kpiPanel(), "KPI Summary");
    addPanelCardTo(pnlRecs,  recommendationsPanel(), "Recommendations");
    addPanelCardTo(pnlReport, monthlyReportPanel(), "Monthly Report");
    addPanelCardTo(pnlLow,   lowStockPanel(), "Low Stock Alert");
}

// Wrap a chart in a titled rounded card and add to target panel
private void addChartCardTo(JPanel target, JFreeChart chart, String title) {
    target.removeAll();
    ChartPanel cp = ChartFactoryUtil.createChartPanel(chart, target.getWidth(), target.getHeight());
    cp.setOpaque(false);
    cp.setBorder(null);
    target.setLayout(new BorderLayout());
    target.add(card(title, cp, target.getWidth(), target.getHeight()), BorderLayout.CENTER);
    target.revalidate();
    target.repaint();

    target.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override public void componentResized(java.awt.event.ComponentEvent e) {
            cp.setPreferredSize(target.getSize());
            target.revalidate();
        }
    });
}

// Wrap a regular panel in a rounded card
private void addPanelCardTo(JPanel target, JPanel content, String title) {
    target.removeAll();
    target.setLayout(new BorderLayout());
    target.add(card(title, content, target.getWidth(), target.getHeight()), BorderLayout.CENTER);
    target.revalidate();
    target.repaint();
}
    
// Rounded card
private javax.swing.JPanel card(String title, java.awt.Component center, int w, int h) {
    JPanel p = new RoundedPanel(16, CARD_BG);
    p.setLayout(new java.awt.BorderLayout());
    p.setPreferredSize(new java.awt.Dimension(w, h));
    p.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 20, 16, 20));

    if (title != null && !title.isEmpty()) {
        javax.swing.JLabel lab = new javax.swing.JLabel(title);
        lab.setForeground(new java.awt.Color(235, 235, 245));
        lab.setFont(CARD_TITLE_FONT);
        lab.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 6, 0));
        p.add(lab, java.awt.BorderLayout.NORTH);
    }

    javax.swing.JPanel inner = new javax.swing.JPanel(new java.awt.BorderLayout());
    inner.setOpaque(false);
    inner.add(center, java.awt.BorderLayout.CENTER);
    p.add(inner, java.awt.BorderLayout.CENTER);
    return p;
}

// KPI panel
private javax.swing.JPanel kpiPanel() {
    javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.GridLayout(1, 2, 24, 0));
    p.setOpaque(false);

    p.add(kpiColumn("Total Inventory", "320 units",
                    "Monthly Sales", "₱1,245,000"));
    p.add(kpiColumn("Net Profit", "₱312,000",
                    "Stock Turnover", "4.2x"));
    return p;
}

private javax.swing.JPanel kpiColumn(String labelTop, String valueTop,
                                    String labelBottom, String valueBottom) {
    javax.swing.JPanel col = new javax.swing.JPanel();
    col.setOpaque(false);
    col.setLayout(new javax.swing.BoxLayout(col, javax.swing.BoxLayout.Y_AXIS));
    col.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));

    col.add(kpiRow(labelTop, valueTop));
    col.add(kpiSeparator());
    col.add(javax.swing.Box.createVerticalStrut(8));
    col.add(kpiRow(labelBottom, valueBottom));
    col.add(kpiSeparator());

    return col;
}

private javax.swing.JPanel kpiRow(String label, String value) {
    javax.swing.JPanel row = new javax.swing.JPanel(new java.awt.BorderLayout());
    row.setOpaque(false);

    java.awt.Color text = new java.awt.Color(230, 238, 248);
    java.awt.Font f = new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 20);

    javax.swing.JLabel l = new javax.swing.JLabel(label);
    l.setForeground(text);
    l.setFont(f);

    javax.swing.JLabel v = new javax.swing.JLabel(value);
    v.setForeground(text);
    v.setFont(f);
    v.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    row.add(l, java.awt.BorderLayout.WEST);
    row.add(v, java.awt.BorderLayout.EAST);
    return row;
}

private javax.swing.JComponent kpiSeparator() {
    javax.swing.JSeparator sep = new javax.swing.JSeparator();
    sep.setForeground(new java.awt.Color(180, 185, 220));
    sep.setBackground(new java.awt.Color(180, 185, 220));
    sep.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 1));
    return sep;
}

// Recommendations table
private javax.swing.JPanel recommendationsPanel() {
    javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.BorderLayout());
    p.setOpaque(false);

    String[] cols = {"Category", "Issue", "Insight", "Recommendation"};
    Object[][] rows = {
        {"Toyota",     "Low Stock",   "44 units remaining", "Reorder within 7 days"},
        {"Ford",       "High Demand", "Sales ↑ 18%",        "Increase inventory"},
        {"Volkswagen", "Low Sales",   "Sales ↓ 12%",        "Apply promo"},
        {"BMW",        "High Margin", "Profit ↑ 22%",       "Push premium ads"}
    };
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(rows, cols) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    };

    javax.swing.JTable table = new javax.swing.JTable(model);
    table.setRowHeight(34);
    table.setIntercellSpacing(new java.awt.Dimension(0, 0));
    table.setShowGrid(true);
    java.awt.Color grid = new java.awt.Color(120, 126, 170);
    table.setGridColor(grid);
    table.setForeground(new java.awt.Color(230, 235, 245));
    table.setBackground(new java.awt.Color(53, 48, 128));
    table.setSelectionBackground(new java.awt.Color(60, 55, 120));
    table.setSelectionForeground(new java.awt.Color(255, 255, 255));
    table.setFocusable(false);

    // Header styling
    javax.swing.table.JTableHeader header = table.getTableHeader();
    header.setReorderingAllowed(false);
    header.setPreferredSize(new java.awt.Dimension(0, 34));
    header.setBackground(new java.awt.Color(72, 68, 130));
    header.setForeground(new java.awt.Color(230, 235, 245));
    header.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 14));
    java.util.Enumeration<?> en = header.getColumnModel().getColumns();
    while (en.hasMoreElements()) {
        javax.swing.table.TableColumn tc = (javax.swing.table.TableColumn) en.nextElement();
        tc.setHeaderRenderer(new HeaderCellRenderer(14, grid));
        tc.setCellRenderer(new BodyCellRenderer(14, grid));
    }

    javax.swing.JScrollPane sp = new javax.swing.JScrollPane(table);
    sp.setBorder(new javax.swing.border.CompoundBorder(
            new javax.swing.border.LineBorder(grid, 1, true),
            javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)
    ));
    sp.getViewport().setBackground(new java.awt.Color(53, 48, 128));
    sp.setOpaque(false);

    p.add(sp, java.awt.BorderLayout.CENTER);
    return p;
}

// Header renderer with padding and bottom divider
private static class HeaderCellRenderer extends javax.swing.table.DefaultTableCellRenderer {
    private final int fontSize;
    private final java.awt.Color grid;
    HeaderCellRenderer(int fontSize, java.awt.Color grid) { this.fontSize = fontSize; this.grid = grid; }
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setBackground(new java.awt.Color(72, 68, 130));
        setForeground(new java.awt.Color(230, 235, 245));
        setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, fontSize));
        setBorder(new javax.swing.border.CompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, grid),
                javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));
        return this;
    }
}

// Body cells
private static class BodyCellRenderer extends javax.swing.table.DefaultTableCellRenderer {
    private final int fontSize;
    private final java.awt.Color grid;
    BodyCellRenderer(int fontSize, java.awt.Color grid) { this.fontSize = fontSize; this.grid = grid; }
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setBackground(new java.awt.Color(53, 48, 128));
        setForeground(new java.awt.Color(230, 235, 245));
        setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, fontSize));
        setBorder(new javax.swing.border.CompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, grid),
                javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8)
        ));
        if (isSelected) {
            setBackground(new java.awt.Color(60, 55, 120));
            setForeground(new java.awt.Color(255, 255, 255));
        }
        return this;
    }
}

// Monthly report
private javax.swing.JPanel monthlyReportPanel() {
    javax.swing.JPanel p = new javax.swing.JPanel();
    p.setOpaque(false);
    p.setLayout(new javax.swing.BoxLayout(p, javax.swing.BoxLayout.Y_AXIS));

    p.add(metricBox("Sales", "85%", new java.awt.Color(110, 177, 219)));
    p.add(javax.swing.Box.createVerticalStrut(12));
    p.add(metricBox("Revenue", "76%", new java.awt.Color(221, 183, 88)));
    p.add(javax.swing.Box.createVerticalStrut(12));
    p.add(metricBox("Expenses", "80%", new java.awt.Color(212, 120, 146)));
    return p;
}

private javax.swing.JPanel metricBox(String label, String value, java.awt.Color bg) {
    javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.BorderLayout());
    p.setOpaque(false);

    javax.swing.JLabel lab = new javax.swing.JLabel(label, javax.swing.SwingConstants.CENTER);
    lab.setForeground(new java.awt.Color(220, 220, 240));
    lab.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 24));
    lab.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
    p.add(lab, java.awt.BorderLayout.NORTH);

    // The colored pill box
    javax.swing.JPanel box = new RoundedPanel(10, bg);
    box.setLayout(new java.awt.GridBagLayout());
    box.setPreferredSize(new java.awt.Dimension(240, 90));

    javax.swing.JLabel val = new javax.swing.JLabel(value);
    val.setForeground(java.awt.Color.WHITE);
    val.setFont(new java.awt.Font("Montserrat", java.awt.Font.BOLD, 18));
    box.add(val);

    javax.swing.JPanel holder = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
    holder.setOpaque(false);
    holder.add(box);

    p.add(holder, java.awt.BorderLayout.CENTER);
    return p;
}

// Low stock alert content
private javax.swing.JPanel lowStockPanel() {
    final java.awt.Color TEXT_PRIMARY = new java.awt.Color(230, 235, 245);
    final java.awt.Color TEXT_SECOND  = new java.awt.Color(190, 198, 220);
    final java.awt.Font COUNT_FONT = new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 32);
    final java.awt.Font BRAND_FONT = new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 18);

    // Margin between alerts
    final int ALERT_GAP = 22;

    javax.swing.JPanel p = new javax.swing.JPanel();
    p.setOpaque(false);
    p.setLayout(new javax.swing.BoxLayout(p, javax.swing.BoxLayout.Y_AXIS));
    p.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));

    java.util.function.BiConsumer<String, Integer> addRow = (brand, units) -> {
        javax.swing.JPanel row = new javax.swing.JPanel();
        row.setOpaque(false);
        row.setLayout(new javax.swing.BoxLayout(row, javax.swing.BoxLayout.Y_AXIS));
        row.setAlignmentX(LEFT_ALIGNMENT);
        row.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));

        javax.swing.JLabel count = new javax.swing.JLabel(units + " units left");
        count.setFont(COUNT_FONT);
        count.setForeground(TEXT_PRIMARY);
        count.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));

        javax.swing.JLabel brandLab = new javax.swing.JLabel(brand);
        brandLab.setFont(BRAND_FONT);
        brandLab.setForeground(TEXT_SECOND);

        row.add(count);
        row.add(brandLab);
        p.add(row);
        p.add(javax.swing.Box.createVerticalStrut(ALERT_GAP));
    };

    addRow.accept("Volkswagen", 44);
    addRow.accept("Honda", 53);
    addRow.accept("Tesla", 45);

    if (p.getComponentCount() > 0) {
        p.remove(p.getComponentCount() - 1);
    }

    return p;
}

// Rounded panel
private static class RoundedPanel extends javax.swing.JPanel {
    private final int arc; private final java.awt.Color bg;
    RoundedPanel(int arc, java.awt.Color bg) { this.arc = arc; this.bg = bg; setOpaque(false); }
    @Override protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(bg);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), arc, arc);
        g2.dispose();
        super.paintComponent(g);
    }
    @Override public boolean isOpaque() { return false; }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlKpi;
    private javax.swing.JPanel pnlLow;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JPanel pnlRecs;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlTrend;
    // End of variables declaration//GEN-END:variables
}
