/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard.admin.UI;

import javax.swing.JFrame;

/**
 *
 * @author Joko
 */
public class AdminUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUI.class.getName());

    /**
     * Creates new form adminUI
     */
    public AdminUI() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        pnlSidebarHeader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlSidebarOptions = new javax.swing.JPanel();
        pnlPlaceholder = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMinimize = new commons.RoundButton();
        btnExit = new commons.RoundButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gradientButton2 = new commons.GradientButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(255, 153, 153));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(262, 1080));
        pnlSidebar.setLayout(new java.awt.BorderLayout());

        pnlSidebarHeader.setBackground(new java.awt.Color(31, 35, 84));
        pnlSidebarHeader.setPreferredSize(new java.awt.Dimension(262, 77));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icons/LEARNLogo.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LEARN");

        javax.swing.GroupLayout pnlSidebarHeaderLayout = new javax.swing.GroupLayout(pnlSidebarHeader);
        pnlSidebarHeader.setLayout(pnlSidebarHeaderLayout);
        pnlSidebarHeaderLayout.setHorizontalGroup(
            pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSidebarHeaderLayout.setVerticalGroup(
            pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                .addGroup(pnlSidebarHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(pnlSidebarHeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlSidebar.add(pnlSidebarHeader, java.awt.BorderLayout.NORTH);

        pnlSidebarOptions.setBackground(new java.awt.Color(28, 32, 77));

        javax.swing.GroupLayout pnlSidebarOptionsLayout = new javax.swing.GroupLayout(pnlSidebarOptions);
        pnlSidebarOptions.setLayout(pnlSidebarOptionsLayout);
        pnlSidebarOptionsLayout.setHorizontalGroup(
            pnlSidebarOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        pnlSidebarOptionsLayout.setVerticalGroup(
            pnlSidebarOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );

        pnlSidebar.add(pnlSidebarOptions, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pnlPlaceholder.setBackground(new java.awt.Color(204, 255, 102));
        pnlPlaceholder.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(45, 45, 114));
        Header.setPreferredSize(new java.awt.Dimension(1658, 77));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 177, 223));
        jLabel3.setText("Date and Time PLaceholder");

        btnMinimize.setBorder(null);
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("–");
        btnMinimize.setBorderColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setBorderPainted(false);
        btnMinimize.setColor(new java.awt.Color(75, 74, 151));
        btnMinimize.setColorClick(new java.awt.Color(48, 43, 116));
        btnMinimize.setColorOver(new java.awt.Color(48, 43, 116));
        btnMinimize.setFocusable(false);
        btnMinimize.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnMinimize.setRadius(10);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(219, 60, 172));
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("x");
        btnExit.setBorderColor(new java.awt.Color(219, 60, 172));
        btnExit.setBorderPainted(false);
        btnExit.setColor(new java.awt.Color(219, 60, 172));
        btnExit.setColorClick(new java.awt.Color(153, 62, 145));
        btnExit.setColorOver(new java.awt.Color(153, 62, 145));
        btnExit.setFocusable(false);
        btnExit.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        btnExit.setRadius(10);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1192, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlPlaceholder.add(Header, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(14, 22, 48));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(182, 181, 228));
        jLabel4.setText("Date and Time PLaceholder");

        gradientButton2.setText("START QUIZ");
        gradientButton2.setColor1(new java.awt.Color(109, 31, 239));
        gradientButton2.setColor2(new java.awt.Color(234, 46, 201));
        gradientButton2.setFocusable(false);
        gradientButton2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        gradientButton2.setHoverColor1(new java.awt.Color(158, 100, 255));
        gradientButton2.setHoverColor2(new java.awt.Color(244, 105, 220));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(gradientButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(124, 124, 124)
                .addComponent(gradientButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );

        pnlPlaceholder.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPlaceholder, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private commons.RoundButton btnExit;
    private commons.RoundButton btnMinimize;
    private commons.GradientButton gradientButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlPlaceholder;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlSidebarHeader;
    private javax.swing.JPanel pnlSidebarOptions;
    // End of variables declaration//GEN-END:variables
}
